In [1]:
import numpy as np
import tensorflow as tf
import message_filters

In [3]:
class FusionNet(tf.keras.Model):
    def __int__(self, c1, c2, c3, c4, num_classes, num_pointts):
        super().__init__()
        same_padding = 'SAME'

        initialize_kernel = tf.keras.initializers.VarianceScaling(scale=2.0)
        initialize_bias = tf.zeros_initializer()
        relu = tf.nn.relu

        #VGG-16
        self.conv1 =  tf.keras.layers.Conv2D(c1, kernel_size=(3,3),strides=(1,1), padding=same_padding, activation=relu, use_bias=True,
                                             kernel_initializer=initialize_kernel, bias_initializer=initialize_bias)

        self.conv2 =  tf.keras.layers.Conv2D(c1, kernel_size=(3,3),strides=(1,1), padding=same_padding, activation=relu, use_bias=True,
                                             kernel_initializer=initialize_kernel, bias_initializer=initialize_bias)

        self.mx_pool1 = tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=same_padding)

        self.conv3 =  tf.keras.layers.Conv2D(c2, kernel_size=(3,3),strides=(1,1), padding=same_padding, activation=relu, use_bias=True,
                                             kernel_initializer=initialize_kernel, bias_initializer=initialize_bias)

        self.conv4 =  tf.keras.layers.Conv2D(c2, kernel_size=(3,3),strides=(1,1), padding=same_padding, activation=relu, use_bias=True,
                                             kernel_initializer=initialize_kernel, bias_initializer=initialize_bias)

        self.mx_pool2 = tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=same_padding)

        self.conv5 =  tf.keras.layers.Conv2D(c3, kernel_size=(3,3),strides=(1,1), padding=same_padding, activation=relu, use_bias=True,
                                             kernel_initializer=initialize_kernel, bias_initializer=initialize_bias)

        self.conv6 =  tf.keras.layers.Conv2D(c3, kernel_size=(3,3),strides=(1,1), padding=same_padding, activation=relu, use_bias=True,
                                             kernel_initializer=initialize_kernel, bias_initializer=initialize_bias)

        self.conv7 =  tf.keras.layers.Conv2D(c3, kernel_size=(3,3),strides=(1,1), padding=same_padding, activation=relu, use_bias=True,
                                             kernel_initializer=initialize_kernel, bias_initializer=initialize_bias)

        self.mx_pool3 = tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=same_padding)

        self.conv8 =  tf.keras.layers.Conv2D(c4, kernel_size=(3,3),strides=(1,1), padding=same_padding, activation=relu, use_bias=True,
                                             kernel_initializer=initialize_kernel, bias_initializer=initialize_bias)

        self.conv9 =  tf.keras.layers.Conv2D(c4, kernel_size=(3,3),strides=(1,1), padding=same_padding, activation=relu, use_bias=True,
                                             kernel_initializer=initialize_kernel, bias_initializer=initialize_bias)

        self.conv10 =  tf.keras.layers.Conv2D(c4, kernel_size=(3,3),strides=(1,1), padding=same_padding, activation=relu, use_bias=True,
                                              kernel_initializer=initialize_kernel, bias_initializer=initialize_bias)

        self.mx_pool4 = tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=same_padding)

        self.conv11 =  tf.keras.layers.Conv2D(c4, kernel_size=(3,3),strides=(1,1), padding=same_padding, activation=relu, use_bias=True,
                                              kernel_initializer=initialize_kernel, bias_initializer=initialize_bias)

        self.conv12 =  tf.keras.layers.Conv2D(c4, kernel_size=(3,3),strides=(1,1), padding=same_padding, activation=relu, use_bias=True,
                                              kernel_initializer=initialize_kernel, bias_initializer=initialize_bias)

        self.conv13 =  tf.keras.layers.Conv2D(c4, kernel_size=(3,3),strides=(1,1), padding=same_padding, activation=relu, use_bias=True,
                                              kernel_initializer=initialize_kernel, bias_initializer=initialize_bias)

        self.mx_pool5 = tf.keras.layers.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=same_padding)


        #PointNet (w/o feature transform)
        self.pn_conv1 = tf.keras.layers.Conv2D(64, kernel_size=(1,3), strides=(1,1), padding=same_padding,
                                               activation=relu, use_bias=True,
                                               kernel_initializer=initialize_kernel,
                                               bias_initializer=initialize_bias)

        self.pn_conv2 = tf.keras.layers.Conv2D(64, kernel_size=(1,1), strides=(1,1), padding=same_padding,
                                               activation=relu, use_bias=True,
                                               kernel_initializer=initialize_kernel,
                                               bias_initializer=initialize_bias)

        self.pn_conv3 = tf.keras.layers.Conv2D(64, kernel_size=(1,1), strides=(1,1), padding=same_padding,
                                               activation=relu, use_bias=True,
                                               kernel_initializer=initialize_kernel,
                                               bias_initializer=initialize_bias)

        self.pn_conv4 = tf.keras.layers.Conv2D(128, kernel_size=(1,1), strides=(1,1), padding=same_padding,
                                               activation=relu, use_bias=True,
                                               kernel_initializer=initialize_kernel,
                                               bias_initializer=initialize_bias)

        self.pn_conv5 = tf.keras.layers.Conv2D(256, kernel_size=(1,1), strides=(1,1), padding=same_padding,
                                               activation=relu, use_bias=True,
                                               kernel_initializer=initialize_kernel,
                                               bias_initializer=initialize_bias)

        self.mx_pool_pn = tf.keras.layers.MaxPool2D(pool_size=(num_classes,1), strides=(num_classes,1),padding=same_padding)










In [12]:
import bagpy
from bagpy import bagreader

In [13]:
reader = bagreader("./135970")

[INFO]  Data folder ./13 already exists. Not creating.


In [14]:
reader.topic_table

Topics                        Types  \
0              /bluetooth_teleop/joy              sensor_msgs/Joy   
1                      /imu/data_raw              sensor_msgs/Imu   
2   /jackal_velocity_controller/odom            nav_msgs/Odometry   
3       /left/image_color/compressed  sensor_msgs/CompressedImage   
4                      /localization  amrl_msgs/Localization2DMsg   
5                        /navsat/fix        sensor_msgs/NavSatFix   
6              /navsat/nmea_sentence           nmea_msgs/Sentence   
7             /navsat/time_reference    sensor_msgs/TimeReference   
8                        /navsat/vel   geometry_msgs/TwistStamped   
9                            /status           jackal_msgs/Status   
10                               /tf           tf2_msgs/TFMessage   
11                        /tf_static           tf2_msgs/TFMessage   
12                  /velodyne_2dscan        sensor_msgs/LaserScan   
13       /velodyne_2dscan_high_beams        sensor_msgs/LaserScan   
14                  /velodyne_points      sensor_msgs/PointCloud2   
15                    /visualization   amrl_msgs/VisualizationMsg   

    Message Count    Frequency  
0           12572    89.261402  
1           18410    83.058814  
2           12918    83.073620  
3            7745    30.011620  
4            6503    24.836075  
5            2585     9.842122  
6           10934  2697.301608  
7            2585     9.844478  
8            2608    11.890369  
9             258     0.998324  
10           8148    25.313707  
11              1          NaN  
12           2563     9.891597  
13           2563     9.894140  
14           2563     9.894700  
15          20693  3480.750207

In [15]:
newMessage = reader.message_by_topic(topic='/velodyne_points')

In [16]:
import pandas as pd
data = pd.read_csv(newMessage)

In [24]:
data.describe()

Time    header.seq  header.stamp.secs  header.stamp.nsecs  \
count  2.563000e+03   2563.000000       2.563000e+03        2.563000e+03   
mean   1.636060e+09  12426.000000       1.636060e+09        5.002783e+08   
std    7.463777e+01    740.018693       7.463801e+01        2.885465e+08   
min    1.636060e+09  11145.000000       1.636060e+09        3.271100e+05   
25%    1.636060e+09  11785.500000       1.636060e+09        2.507025e+08   
50%    1.636060e+09  12426.000000       1.636060e+09        5.005145e+08   
75%    1.636060e+09  13066.500000       1.636060e+09        7.498126e+08   
max    1.636060e+09  13707.000000       1.636060e+09        9.999185e+08   

       height         width  point_step  row_step  
count  2563.0   2563.000000      2563.0    2563.0  
mean      1.0  22979.747171        22.0       0.0  
std       0.0    522.128391         0.0       0.0  
min       1.0  21325.000000        22.0       0.0  
25%       1.0  22664.500000        22.0       0.0  
50%       1.0  22955.000000        22.0       0.0  
75%       1.0  23240.500000        22.0       0.0  
max       1.0  24319.000000        22.0       0.0

In [17]:
data

Time  header.seq  header.stamp.secs  header.stamp.nsecs  \
0     1.636060e+09       11145         1636060137           391200781   
1     1.636060e+09       11146         1636060137           492090225   
2     1.636060e+09       11147         1636060137           592961550   
3     1.636060e+09       11148         1636060137           693787336   
4     1.636060e+09       11149         1636060137           794620275   
...            ...         ...                ...                 ...   
2558  1.636060e+09       13703         1636060395           389232397   
2559  1.636060e+09       13704         1636060395           490171909   
2560  1.636060e+09       13705         1636060395           590950489   
2561  1.636060e+09       13706         1636060395           691891432   
2562  1.636060e+09       13707         1636060395           792759895   

     header.frame_id  height  width  \
0           velodyne       1  23203   
1           velodyne       1  23396   
2           velodyne       1  23323   
3           velodyne       1  23358   
4           velodyne       1  23398   
...              ...     ...    ...   
2558        velodyne       1  21677   
2559        velodyne       1  21729   
2560        velodyne       1  21772   
2561        velodyne       1  21693   
2562        velodyne       1  21561   

                                                 fields  is_bigendian  \
0     [name: "x"\noffset: 0\ndatatype: 7\ncount: 1, ...         False   
1     [name: "x"\noffset: 0\ndatatype: 7\ncount: 1, ...         False   
2     [name: "x"\noffset: 0\ndatatype: 7\ncount: 1, ...         False   
3     [name: "x"\noffset: 0\ndatatype: 7\ncount: 1, ...         False   
4     [name: "x"\noffset: 0\ndatatype: 7\ncount: 1, ...         False   
...                                                 ...           ...   
2558  [name: "x"\noffset: 0\ndatatype: 7\ncount: 1, ...         False   
2559  [name: "x"\noffset: 0\ndatatype: 7\ncount: 1, ...         False   
2560  [name: "x"\noffset: 0\ndatatype: 7\ncount: 1, ...         False   
2561  [name: "x"\noffset: 0\ndatatype: 7\ncount: 1, ...         False   
2562  [name: "x"\noffset: 0\ndatatype: 7\ncount: 1, ...         False   

      point_step  row_step                                               data  \
0             22         0  b'"\xc8Z=i\x1d\xb6?\xe0S\xc3\xbe\x00\x00@@\x00...   
1             22         0  b'\x9c\xf0\x05>\xaaz\xb4?|D\xc2\xbe\x00\x00\x0...   
2             22         0  b'm\xe9L>\\.\xb7?3>\xc6\xbe\x00\x00\xc0@\x00\x...   
3             22         0  b'\xe3e\x87>\xc3\xca\xae?v\xd2\xbe\xbe\x00\x00...   
4             22         0  b'-\xf6\xad>2n\xae?f\xad\xc0\xbe\x00\x00\xe0@\...   
...          ...       ...                                                ...   
2558          22         0  b'\x02M\xc3=\x87o\xc6?\xae\x15\xd5\xbe\x00\x00...   
2559          22         0  b'\xa7\x8b+>k\xeb\xc1?\xf7\x1b\xd1\xbe\x00\x00...   
2560          22         0  b'vyt>\x9b\xf1\xc0?\xcf_\xd1\xbe\x00\x00\xe0@\...   
2561          22         0  b'\x15\xcc\xa3>\xf2<\xbd?\xe1\x84\xcf\xbe\x00\...   
2562          22         0  b'\xa0\x9e\xcf>\xe8\x87\xba?\xe1\x84\xcf\xbe\x...   

      is_dense  
0         True  
1         True  
2         True  
3         True  
4         True  
...        ...  
2558      True  
2559      True  
2560      True  
2561      True  
2562      True  

[2563 rows x 13 columns]

In [26]:
reader.animate_pointcloud

<bound method bagreader.animate_pointcloud of <bagpy.bagreader.bagreader object at 0x28ea6df70>>

In [28]:
p = reader.topic_table.get('/velodyne_points')

In [107]:
k = tf.ones((2, 2,3))

In [108]:
k.shape

TensorShape([2, 2, 3])

In [109]:
k

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [110]:
k.get_shape()[1]

2

In [111]:
y = tf.expand_dims(k, -1)

In [112]:
y

<tf.Tensor: shape=(2, 2, 3, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]]], dtype=float32)>

In [113]:
convpn1 = tf.keras.layers.Conv2D(2, kernel_size=(1,3),
                                      strides=(1,1),padding="SAME",
                                      activation = tf.nn.relu,use_bias=True,
                                      kernel_initializer = tf.keras.initializers.VarianceScaling(scale=2.0),
                                      bias_initializer=tf.zeros_initializer())

In [114]:
d = convpn1(y)

In [115]:
d.shape

TensorShape([2, 2, 3, 2])

In [116]:
d

<tf.Tensor: shape=(2, 2, 3, 2), dtype=float32, numpy=
array([[[[0.4315133 , 0.        ],
         [1.0586503 , 0.38118994],
         [1.1907346 , 1.3848988 ]],

        [[0.4315133 , 0.        ],
         [1.0586503 , 0.38118994],
         [1.1907346 , 1.3848988 ]]],


       [[[0.4315133 , 0.        ],
         [1.0586503 , 0.38118994],
         [1.1907346 , 1.3848988 ]],

        [[0.4315133 , 0.        ],
         [1.0586503 , 0.38118994],
         [1.1907346 , 1.3848988 ]]]], dtype=float32)>

In [117]:
y

<tf.Tensor: shape=(2, 2, 3, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]]], dtype=float32)>

In [77]:
y[0][0]

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.]], dtype=float32)>

In [81]:
d = convpn1(y)

In [118]:
convpn2 = tf.keras.layers.Conv2D(2, kernel_size=(3,1),
                                      strides=(1,1),padding="SAME",
                                      activation = tf.nn.relu,use_bias=True,
                                      kernel_initializer = tf.keras.initializers.VarianceScaling(scale=2.0),
                                      bias_initializer=tf.zeros_initializer())

In [121]:
d = convpn2(y)

In [122]:
d

<tf.Tensor: shape=(2, 2, 3, 2), dtype=float32, numpy=
array([[[[2.3391283 , 0.97100234],
         [2.3391283 , 0.97100234],
         [2.3391283 , 0.97100234]],

        [[2.475854  , 0.37251323],
         [2.475854  , 0.37251323],
         [2.475854  , 0.37251323]]],


       [[[2.3391283 , 0.97100234],
         [2.3391283 , 0.97100234],
         [2.3391283 , 0.97100234]],

        [[2.475854  , 0.37251323],
         [2.475854  , 0.37251323],
         [2.475854  , 0.37251323]]]], dtype=float32)>

In [22]:
import numpy as np
import rosbag
import sensor_msgs.point_cloud2 as pc2
x = []
count = 0;
def convert_pc_msg_to_np(msg, t):
    for point in pc2.read_points(msg, skip_nans=True):
            pt_x = point[0]
            pt_y = point[1]
            pt_z = point[2]
            x.append((pt_x,pt_y,pt_z,t))



# To run it offline on a rosbag use:
for topic, msg, t in rosbag.Bag('./135970').read_messages(topics=["/velodyne_points"]):
        print(topic)
        convert_pc_msg_to_np(msg, t)
        count +=1
        print(msg.header)
        if count == 100:
            break


/velodyne_points
seq: 11145
stamp: 
  secs: 1636060137
  nsecs: 391200781
frame_id: "velodyne"
/velodyne_points
seq: 11146
stamp: 
  secs: 1636060137
  nsecs: 492090225
frame_id: "velodyne"
/velodyne_points
seq: 11147
stamp: 
  secs: 1636060137
  nsecs: 592961550
frame_id: "velodyne"
/velodyne_points
seq: 11148
stamp: 
  secs: 1636060137
  nsecs: 693787336
frame_id: "velodyne"
/velodyne_points
seq: 11149
stamp: 
  secs: 1636060137
  nsecs: 794620275
frame_id: "velodyne"
/velodyne_points
seq: 11150
stamp: 
  secs: 1636060137
  nsecs: 895515919
frame_id: "velodyne"
/velodyne_points
seq: 11151
stamp: 
  secs: 1636060137
  nsecs: 996394634
frame_id: "velodyne"
/velodyne_points
seq: 11152
stamp: 
  secs: 1636060138
  nsecs:  97208500
frame_id: "velodyne"
/velodyne_points
seq: 11153
stamp: 
  secs: 1636060138
  nsecs: 198041439
frame_id: "velodyne"
/velodyne_points
seq: 11154
stamp: 
  secs: 1636060138
  nsecs: 298948288
frame_id: "velodyne"
/velodyne_points
seq: 11155
stamp: 
  secs: 163606

In [2]:
x

[(0.0534135177731514,
  1.4227725267410278,
  -0.3814992904663086,
  rospy.Time[1636060137400502754]),
 (0.24969793856143951,
  6.620284080505371,
  0.11563964933156967,
  rospy.Time[1636060137400502754]),
 (0.060358207672834396,
  1.5929263830184937,
  -0.3680199384689331,
  rospy.Time[1636060137400502754]),
 (0.2520815134048462,
  6.622109413146973,
  0.3473014235496521,
  rospy.Time[1636060137400502754]),
 (0.06960216164588928,
  1.8284289836883545,
  -0.35566797852516174,
  rospy.Time[1636060137400502754]),
 (0.2538379728794098,
  6.63777494430542,
  0.581154465675354,
  rospy.Time[1636060137400502754]),
 (0.08341256529092789,
  2.1713128089904785,
  -0.34415584802627563,
  rospy.Time[1636060137400502754]),
 (0.2555994391441345,
  6.623293399810791,
  0.8138435482978821,
  rospy.Time[1636060137400502754]),
 (0.10234841704368591,
  2.6401748657226562,
  -0.32441622018814087,
  rospy.Time[1636060137400502754]),
 (0.2585673928260803,
  6.640135288238525,
  1.0524911880493164,
  rospy.

In [4]:
import cv2
import matplotlib.pyplot as plt
import rosbag

In [21]:
i=10

b = rosbag.Bag('./135970')
for topic, msg, t in b.read_messages(topics=[" "]):
    np_arr = np.frombuffer(msg.data, np.uint8)
    print(f"{np_arr.shape = }")
    print(40 * "-")
    # cv_image = cv2.imdecode(np_arr, cv2.IMREAD_COLOR)
    # print(t.from_sec())
    print(msg.header)
    # cv2.imwrite(str(msg.header.seq) + ".png", cv_image)
    # print(f"{cv_image.shape = }")
    # print(40 * "-")
    # plt.imshow(cv_image[:, :, (2, 1, 0)])
    # plt.show()
    # print(np.array(msg.data).astype(np.uint8).shape)
    if i == 1:
        break
    i += 1
b.close()

np_arr.shape = (207653,)
----------------------------------------
seq: 608
stamp: 
  secs: 1636060137
  nsecs: 491192922
frame_id: "left_camera"
np_arr.shape = (207826,)
----------------------------------------
seq: 609
stamp: 
  secs: 1636060137
  nsecs: 523549291
frame_id: "left_camera"
np_arr.shape = (199176,)
----------------------------------------
seq: 610
stamp: 
  secs: 1636060137
  nsecs: 555679803
frame_id: "left_camera"
np_arr.shape = (197049,)
----------------------------------------
seq: 611
stamp: 
  secs: 1636060137
  nsecs: 589060830
frame_id: "left_camera"
np_arr.shape = (191539,)
----------------------------------------
seq: 612
stamp: 
  secs: 1636060137
  nsecs: 622741310
frame_id: "left_camera"
np_arr.shape = (189584,)
----------------------------------------
seq: 613
stamp: 
  secs: 1636060137
  nsecs: 657713972
frame_id: "left_camera"
np_arr.shape = (183479,)
----------------------------------------
seq: 614
stamp: 
  secs: 1636060137
  nsecs: 689792967
frame_id:

In [9]:
b.get_message_count('/velodyne_points')

2563